---
  version: '3.7'

  x-commons-secrets-java:
    &java-secrets
    secrets:
      - source: ssl_crt
        target: /home/spring/ssl.crt
      - source: ssl_key
        target: /home/spring/ssl.key
      - source: water_auth_crt
        target: /certificates/water-auth.crt
      - source: ssl_crt
        target: /certificates/mlr.crt

  x-commons-secrets-python:
    &python-secrets
    secrets:
      - source: ssl_crt
        target: /home/python/certificates/ssl.crt
      - source: ssl_key
        target: /home/python/certificates/ssl.key
      - source: water_auth_crt
        target: /home/python/certificates/water-auth.crt

  secrets:
    ssl_crt:
      file: ./configuration/config/certificates/ssl.crt
    ssl_key:
      file: ./configuration/config/certificates/ssl.key
    water_auth_crt:
      file: ./configuration/config/certificates/water-auth.crt
    water_auth_key:
      file: ./configuration/config/certificates/water-auth.key

  networks:
    mlr-it-net:
      name: mlr-it-net

  services:
    mock-s3:
      image: andrewgaul/s3proxy
      env_file:
        - configuration/config/mock-s3/config.env
      networks:
        mlr-it-net:
          aliases:
            - s3.mock.server
      hostname: s3.mock.server
      ports:
        - "8080:80"

    smtp-server:
      image: digiplant/fake-smtp:latest
      networks:
        mlr-it-net:
          aliases:
            - smtp.notification.server
      hostname: smtp.notification.server

    mlr-legacy-db:
      image: code.chs.usgs.gov:5001/wma/docker/mlr/mlr-legacy-db:latest
      container_name: mlr-legacy-db
      env_file:
        - configuration/config/common/config.env
        - configuration/secrets/common/secrets.env
        - configuration/config/mlr-legacy-db/config.env
        - configuration/secrets/mlr-legacy-db/secrets.env
      networks:
        mlr-it-net:
          aliases:
            - mlr.legacy.db
      ports:
        - "5432:5432"

    water-auth-server:
      image: code.chs.usgs.gov:5001/wma-devops-public/waterauth-server:latest
      container_name: water-auth-server
      env_file:
        - configuration/config/common/config.env
        - configuration/secrets/common/secrets.env
        - configuration/config/water-auth-server/config.env
        - configuration/secrets/water-auth-server/secrets.env
      secrets:
        - source: water_auth_crt
          target: /home/spring/ssl.crt
        - source: water_auth_key
          target: /home/spring/ssl.key
        - source: water_auth_crt
          target: /home/spring/oauth-wildcard-sign.crt
        - source: water_auth_key
          target: /home/spring/oauth-wildcard-sign.key
        - source: water_auth_crt
          target: /home/spring/saml-wildcard-sign.crt
        - source: water_auth_key
          target: /home/spring/saml-wildcard-sign.key
      networks:
        mlr-it-net:
          aliases:
            - water-auth
      ports:
        - 8443:8443

    mlr-legacy:
      image: code.chs.usgs.gov:5001/wma/docker/mlr/mlr-legacy:latest
      container_name: mlr-legacy
      env_file:
        - configuration/config/common/config.env
        - configuration/secrets/common/secrets.env
        - configuration/config/mlr-legacy/config.env
        - configuration/secrets/mlr-legacy/secrets.env
      command: "./wait-for.sh water-auth:8443 -t 60 -- ./wait-for.sh mlr.legacy.db:5432 -t 60 -- ./entrypoint.sh"
      networks:
        mlr-it-net:
          aliases:
            - mlr-int
      ports:
        - "6010:6010"
      depends_on:
        - water-auth-server
        - mlr-legacy-db
      << : *java-secrets

    mlr-notification:
      image: code.chs.usgs.gov:5001/wma/docker/mlr/mlr-notification:latest
      container_name: mlr-notification
      env_file:
        - configuration/config/common/config.env
        - configuration/secrets/common/secrets.env
        - configuration/config/mlr-notification/config.env
        - configuration/secrets/mlr-notification/secrets.env
      command: "./wait-for.sh water-auth:8443 -t 60 -- ./entrypoint.sh"
      networks:
        mlr-it-net:
          aliases:
            - mlr-int
      ports:
        - "6025:6025"
      depends_on:
        - water-auth-server
        - smtp-server
      << : *java-secrets

    mlr-legacy-transformer:
      image: code.chs.usgs.gov:5001/wma/docker/mlr/mlr-legacy-transformer:latest
      container_name: mlr-legacy-transformer
      env_file:
        - configuration/config/common/config.env
        - configuration/secrets/common/secrets.env
        - configuration/config/mlr-legacy-transformer/config.env
        - configuration/secrets/mlr-legacy-transformer/secrets.env
      command: "./wait-for.sh water-auth:8443 -t 60 -- ./entrypoint.sh"
      networks:
        mlr-it-net:
          aliases:
            - mlr-int
      ports:
        - "6020:6020"
      depends_on:
        - water-auth-server
      << : *python-secrets

    mlr-wsc-file-exporter:
      image: code.chs.usgs.gov:5001/wma/docker/mlr/mlr-wsc-file-exporter:latest
      container_name: mlr-wsc-file-exporter
      env_file:
        - configuration/config/common/config.env
        - configuration/secrets/common/secrets.env
        - configuration/config/mlr-wsc-file-exporter/config.env
        - configuration/secrets/mlr-wsc-file-exporter/secrets.env
      command: "./wait-for.sh water-auth:8443 -t 60 -- ./entrypoint.sh"
      networks:
        mlr-it-net:
          aliases:
            - mlr-int
      ports:
        - "6024:6024"
      depends_on:
        - water-auth-server
      << : *python-secrets

    mlr-validator:
      image: code.chs.usgs.gov:5001/wma/osd/mlr/mlr-validator:latest
      container_name: mlr-validator
      volumes:
        - type: bind
          source: ./remote-references
          target: /home/python/remote-references
      env_file:
        - configuration/config/common/config.env
        - configuration/secrets/common/secrets.env
        - configuration/config/mlr-validator/config.env
        - configuration/secrets/mlr-validator/secrets.env
      command: "./wait-for.sh water-auth:8443 -t 60 -- ./entrypoint.sh"
      networks:
        mlr-it-net:
          aliases:
            - mlr-int
      ports:
        - "6027:6027"
      depends_on:
        - water-auth-server
      << : *python-secrets

    mlr-ddot-ingester:
      image: code.chs.usgs.gov:5001/wma/docker/mlr/mlr-ddot-ingester:latest
      container_name: mlr-ddot-ingester
      env_file:
        - configuration/config/common/config.env
        - configuration/secrets/common/secrets.env
        - configuration/config/mlr-ddot-ingester/config.env
        - configuration/secrets/mlr-ddot-ingester/secrets.env
      command: "./wait-for.sh water-auth:8443 -t 60 -- ./entrypoint.sh"
      networks:
        mlr-it-net:
          aliases:
            - mlr-int
      ports:
        - 6028:6028
      depends_on:
        - water-auth-server
      << : *python-secrets

    mlr-gateway:
      image: code.chs.usgs.gov:5001/wma/docker/mlr/mlr-gateway:latest
      container_name: mlr-gateway
      env_file:
        - configuration/config/common/config.env
        - configuration/secrets/common/secrets.env
        - configuration/config/mlr-gateway/config.env
        - configuration/secrets/mlr-gateway/secrets.env
      command: "./wait-for.sh water-auth:8443 -t 60 -- ./wait-for.sh mlr.legacy.db:5432 -t 60 -- ./entrypoint.sh"
      networks:
        mlr-it-net:
          aliases:
            - mlr-int
      ports:
        - 6026:6026
      depends_on:
        - mlr-legacy-db
        - water-auth-server
      << : *java-secrets
