---
  version: '3.7'

  x-commons-depends:
    &depends-on-keycloak
    depends_on:
      - mlr-keycloak

  x-commons-secrets-java:
    &java-secrets
    secrets:
      - source: ssl_crt
        target: /home/spring/ssl.crt
      - source: ssl_key
        target: /home/spring/ssl.key
 

  x-commons-secrets-python:
    &python-secrets
    secrets:
      - source: ssl_crt
        target: /home/python/certificates/ssl.crt
      - source: ssl_key
        target: /home/python/certificates/ssl.key

  secrets:
    ssl_crt:
      file: ./configuration/config/certificates/wildcard/ssl.crt
    ssl_key:
      file: ./configuration/config/certificates/wildcard/ssl.key

  networks:
    mlr-it-net:
      name: mlr-it-net

  services:
    mock-s3:
      image: andrewgaul/s3proxy
      env_file:
        - configuration/config/mock-s3/config.env
      networks:
        mlr-it-net:
          aliases:
            - s3.mock.server
      hostname: s3.mock.server
      ports:
        - "8080:80"

    smtp-server:
      image: digiplant/fake-smtp:latest
      networks:
        mlr-it-net:
          aliases:
            - smtp.notification.server
      hostname: smtp.notification.server

    mlr-legacy-db:
      image: code.chs.usgs.gov:5001/wma/docker/mlr/mlr-legacy-db:latest
      container_name: mlr-legacy-db
      env_file:
        - configuration/config/common/config.env
        - configuration/secrets/common/secrets.env
        - configuration/config/mlr-legacy-db/config.env
        - configuration/secrets/mlr-legacy-db/secrets.env
      networks:
        mlr-it-net:
          aliases:
            - mlr.legacy.db
      ports:
        - "5432:5432"

    mlr-keycloak:
      image: jboss/keycloak:10.0.0
      container_name: mlr-keycloak
      networks:
        mlr-it-net:
          aliases:
            - mlr-keycloak
      hostname: mlr-keycloak
      ports:
        - "9080:9080"
        - "9443:9443"
      #command: ["-b", "0.0.0.0", "-Djboss.socket.binding.port-offset=1000"]
      environment:
        - PROXY_ADDRESS_FORWARDING=true
        - DB_VENDOR=h2
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=admin
      entrypoint: "/opt/jboss/tools/docker-entrypoint.sh -b 0.0.0.0 -Dkeycloak.profile.feature.upload_scripts=enabled -Djboss.socket.binding.port-offset=1000 -Djgroups.bind_addr=127.0.0.1 -Djboss.bind.address.private=0.0.0.0"
      healthcheck:
        test: ["CMD", "curl", "-fk", "https://localhost:9443/auth/"]
        interval: 5s
        timeout: 10s
        retries: 10
        start_period: 40s

      secrets:
        - source: ssl_crt
          target: /etc/x509/https/tls.crt
        - source: ssl_key
          target: /etc/x509/https/tls.key
      volumes:
        - type: bind
          source: ./configuration/config/keycloak/local_realm.json
          target: /tmp/local_realm.json
        - type: bind
          source: ./configuration/config/keycloak/load_realm.sh
          target: /tmp/load_realm.sh
        - type: bind
          source: ./configuration/config/keycloak/start_load_keycloak.sh
          target: /opt/jboss/startup-scripts/start_load_keycloak.sh

    mlr-legacy:
      image: code.chs.usgs.gov:5001/wma/docker/mlr/mlr-legacy:latest
      container_name: mlr-legacy
      env_file:
        - configuration/config/common/config.env
        - configuration/secrets/common/secrets.env
        - configuration/config/mlr-legacy/config.env
        - configuration/secrets/mlr-legacy/secrets.env
      command: "./wait-for.sh mlr-keycloak:9443 -t 120 -- ./wait-for.sh mlr.legacy.db:5432 -t 120 -- ./entrypoint.sh"
      networks:
        mlr-it-net:
          aliases:
            - mlr-int
      ports:
        - "6010:6010"
      depends_on:
        - mlr-keycloak
        - mlr-legacy-db
      << : *java-secrets

    mlr-notification:
      image: code.chs.usgs.gov:5001/wma/docker/mlr/mlr-notification:latest
      container_name: mlr-notification
      env_file:
        - configuration/config/common/config.env
        - configuration/secrets/common/secrets.env
        - configuration/config/mlr-notification/config.env
        - configuration/secrets/mlr-notification/secrets.env
      command: "./wait-for.sh mlr-keycloak:9443 -t 120 -- ./entrypoint.sh"
      networks:
        mlr-it-net:
          aliases:
            - mlr-int
      ports:
        - "6025:6025"
      depends_on:
        - mlr-keycloak
        - smtp-server
      << : *java-secrets

    mlr-legacy-transformer:
      image: code.chs.usgs.gov:5001/wma/docker/mlr/mlr-legacy-transformer:latest
      container_name: mlr-legacy-transformer
      env_file:
        - configuration/config/common/config.env
        - configuration/secrets/common/secrets.env
        - configuration/config/mlr-legacy-transformer/config.env
        - configuration/secrets/mlr-legacy-transformer/secrets.env
      command: "./wait-for.sh mlr-keycloak:9443 -t 120 -- ./entrypoint.sh"
      networks:
        mlr-it-net:
          aliases:
            - mlr-int
      ports:
        - "6020:6020"
      depends_on:
        - mlr-keycloak
      << : *python-secrets

    mlr-wsc-file-exporter:
      image: code.chs.usgs.gov:5001/wma/docker/mlr/mlr-wsc-file-exporter:latest
      container_name: mlr-wsc-file-exporter
      env_file:
        - configuration/config/common/config.env
        - configuration/secrets/common/secrets.env
        - configuration/config/mlr-wsc-file-exporter/config.env
        - configuration/secrets/mlr-wsc-file-exporter/secrets.env
      command: "./wait-for.sh mlr-keycloak:9443 -t 120 -- ./entrypoint.sh"
      networks:
        mlr-it-net:
          aliases:
            - mlr-int
      ports:
        - "6024:6024"
      depends_on:
        - mlr-keycloak
      << : *python-secrets

    mlr-validator:
      image: code.chs.usgs.gov:5001/wma/osd/mlr/mlr-validator:latest
      container_name: mlr-validator
      volumes:
        - type: bind
          source: ./remote-references
          target: /home/python/remote-references
      env_file:
        - configuration/config/common/config.env
        - configuration/secrets/common/secrets.env
        - configuration/config/mlr-validator/config.env
        - configuration/secrets/mlr-validator/secrets.env
      command: "./wait-for.sh mlr-keycloak:9443 -t 150 -- ash -xv entrypoint.sh"
      networks:
        mlr-it-net:
          aliases:
            - mlr-int
      ports:
        - "6027:6027"
      depends_on:
        - mlr-keycloak
      << : *python-secrets

    mlr-ddot-ingester:
      image: code.chs.usgs.gov:5001/wma/docker/mlr/mlr-ddot-ingester:latest
      container_name: mlr-ddot-ingester
      env_file:
        - configuration/config/common/config.env
        - configuration/secrets/common/secrets.env
        - configuration/config/mlr-ddot-ingester/config.env
        - configuration/secrets/mlr-ddot-ingester/secrets.env
      command: "./wait-for.sh mlr-keycloak:9443 -t 120 -- ./entrypoint.sh"
      networks:
        mlr-it-net:
          aliases:
            - mlr-int
      ports:
        - 6028:6028
      depends_on:
        - mlr-keycloak
      << : *python-secrets

    mlr-gateway:
      image: code.chs.usgs.gov:5001/wma/docker/mlr/mlr-gateway:latest
      container_name: mlr-gateway
      env_file:
        - configuration/config/common/config.env
        - configuration/secrets/common/secrets.env
        - configuration/config/mlr-gateway/config.env
        - configuration/secrets/mlr-gateway/secrets.env
      command: "./wait-for.sh mlr-keycloak:9443 -t 120 -- ./wait-for.sh mlr.legacy.db:5432 -t 120 -- ./entrypoint.sh"
      networks:
        mlr-it-net:
          aliases:
            - mlr-int
      ports:
        - 6026:6026
      depends_on:
        - mlr-legacy-db
        - mlr-keycloak
      << : *java-secrets
